name = "Nomifactory (GTCEu Port) - Szymzal version"
author = "Szymzal"
version = "1.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8cce80ad8dfc109140933bc95bdae7cb6a2ac424ad42a7cb598fd7d78a124b1"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
