name = "Nomifactory (GTCEu Port) - Szymzal version"
author = "Szymzal"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fa4e2c1b1bb31228a736047580abb62b3399e64a287a496c5878f9bed5740dd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
