name = "Nomifactory (GTCEu Port) - Szymzal version"
author = "Szymzal"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54723fd21a03fdf578047ee95e464da3ed042c707807ffc622d99e6e4d2facfa"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
