name = "Nomifactory (GTCEu Port) - Szymzal version"
author = "Szymzal"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f244b10a1fc5c9fd6a386dba531ea2cc9c4536cca244671e0dc50fcd50adc0e0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
