name = "Nomifactory (GTCEu Port) - Szymzal version"
author = "Szymzal"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e69a2975d801803695701dfd63aa977e5115ca45e122d192657d51338f04e0c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
